# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2025-06-26 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sign_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
