# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2025-06-26 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sign_in',
            new_name='Sign_up',
        ),
    ]
