# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2025-06-28 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_profile_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile_model',
            old_name='portfolio',
            new_name='portfolio_site',
        ),
    ]
