# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2025-06-30 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20250628_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sign_up',
        ),
    ]
